title: Chris Schmidt # your name (or website title) here
logo: "/images/me3.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Recent recipient of master's degree in applied mathematics. Interested in and growing skills in data analytics, engineering, and science.  
  <br><br>
  Husband, father, brother, son. omnem gloriam Dei 
  <br><br>
  <a href="https://https://www.linkedin.com/in/chris-schmidt-94526a10//in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: 199901983 # your Google Analytics tracking ID here
